from enum import Enum

class ComplicationCodeType(Enum):
    ABD = "ABD"  # Abszeß in einem Drainagekanal
    ABS = "ABS"  # Abszeß, intraabdominaler oder intrathorakaler
    ASF = "ASF"  # Abszeß, subfaszialer
    ANI = "ANI"  # Akute Niereninsuffizienz
    AEP = "AEP"  # Alkoholentzugspsychose
    ALR = "ALR"  # Allergische Reaktion ohne Schocksymptomatik
    ANS = "ANS"  # Anaphylaktischer Schock
    AEE = "AEE"  # Anastomoseninsuffizienz einer Enterostomie
    API = "API"  # Apoplektischer Insult
    BIF = "BIF"  # Biliäre Fistel
    BOG = "BOG"  # Blutung, obere gastrointestinale (z.B "Stressulkus")
    BOE = "BOE"  # Bolusverlegung eines Endotubus
    BSI = "BSI"  # Bronchusstumpfinsuffizienz
    CHI = "CHI"  # Cholangitis
    DAI = "DAI"  # Darmanastomoseinsuffizienz
    DPS = "DPS"  # Darmpassagestörungen (z.B. protrahierte Atonie, Subileus, Ileus)
    DIC = "DIC"  # Disseminierte intravasale Koagulopathie
    DEP = "DEP"  # Drogenentzugspsychose
    DLU = "DLU"  # Druck- und Lagerungsschäden, z.B. Dekubitalulzera
    DSI = "DSI"  # Duodenalstumpfinsuffizienz
    ENF = "ENF"  # Enterale Fistel
    GER = "GER"  # Gerinnungsstörung
    HEM = "HEM"  # Hämatemesis
    HUR = "HUR"  # Hämaturie
    HAE = "HAE"  # Hämorrhagischer Schock
    HFI = "HFI"  # Harnfistel
    HNK = "HNK"  # Hautnekrose im Operationsbereich
    HZI = "HZI"  # Herzinsuffizienz
    HRS = "HRS"  # Herzrhythmusstörungen
    HNA = "HNA"  # Hirnnervenausfälle
    HOP = "HOP"  # Hirnorganisches Psychosyndrom (z.B. "Durchgangssyndrom")
    HYB = "HYB"  # Hyperbilirubinämie
    HYF = "HYF"  # Hypopharynxfistel
    IFV = "IFV"  # Ileofemorale Venenthrombose
    KAS = "KAS"  # Kardiogener Schock
    KES = "KES"  # Komplikationen einer Stomaanlage
    KIM = "KIM"  # Komplikation eines Implantates (z.B. Dislokation)
    KRA = "KRA"  # Krampfanfall
    KDS = "KDS"  # Kurzdarmsyndrom
    LEV = "LEV"  # Leberversagen
    LOE = "LOE"  # Lungenödem
    LYF = "LYF"  # Lymphfistel
    LYE = "LYE"  # Lymphozele
    MES = "MES"  # Magenentleerungsstörung
    MIL = "MIL"  # Mechanischer Ileus
    MED = "MED"  # Mediastinitis
    MAT = "MAT"  # Mesenterialarterien- oder -venenthrombose
    MYI = "MYI"  # Myokardinfarkt
    RNB = "RNB"  # Nachblutung, revisionsbedürftig
    NAB = "NAB"  # Nachblutung, nicht revisionsbedürftig
    NIN = "NIN"  # Nahtinsuffizienz, anderweitig nicht erwähnt
    OES = "OES"  # Ösophagitis
    OSM = "OSM"  # Osteitis, Osteomyelitis
    PAF = "PAF"  # Pankreasfistel
    PIT = "PIT"  # Pankreatitis
    PAB = "PAB"  # Peranale Blutung
    PPA = "PPA"  # Periphere Parese
    PAV = "PAV"  # Peripherer arterieller Verschluss
    PER = "PER"  # Peritonitis
    PLB = "PLB"  # Platzbauch
    PEY = "PEY"  # Pleuraempyem
    PLE = "PLE"  # Pleuraerguss
    PMN = "PMN"  # Pneumonie
    PNT = "PNT"  # Pneumothorax
    PDA = "PDA"  # Protrahierte Darmatonie (paralytischer Ileus)
    PAE = "PAE"  # Pulmonalarterienembolie
    RPA = "RPA"  # Rekurrensparese
    RIN = "RIN"  # Respiratorische Insuffizienz
    SKI = "SKI"  # Septische Komplikation eines Implantates
    SES = "SES"  # Septischer Schock
    SFH = "SFH"  # Störungen des Flüssigkeits-, Elektrolyt- und Säurebasenhaushaltes
    STK = "STK"  # Stomakomplikation (z.B. Blutung, Nekrose, Stenose)
    TZP = "TZP"  # Thrombozytopenie
    TIA = "TIA"  # TIA oder RIND
    TRZ = "TRZ"  # Transfusionszwischenfall
    WUH = "WUH"  # Wundhämatom (konservativ therapiert)
    WSS = "WSS"  # Wundheilungsstörung, subkutane
